### ISSUE TITLE
Automatic ISBN hyphenation

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#125]

**Comment by ja573** [comment]
could be tackled as part of #233

**Comment by rhigman** [comment]
As some crates exist for handling ISBNs already, it would be preferable to use one of them rather than re-implementing the ISBN hyphenation rules. I tried adding `isbn2` (currently at v0.4.0) and `isbnid` (currently at v0.1.3) to `Cargo.toml`, however, both caused compile errors in existing code due to a change in the `uuid` version, e.g.:
```
thoth-export-server/src/specification/handler.rs:35
no function or associated item named `update_parameter` found for struct `actix_web::web::Path<(std::string::String, uuid::Uuid)>` in the current scope
function or associated item not found in `actix_web::web::Path<(std::string::String, uuid::Uuid)>`
```
We should discuss whether this can be resolved and therefore whether either of the crates can be used.

**Comment by rhigman** [comment]
> As some crates exist for handling ISBNs already, it would be preferable to use one of them rather than re-implementing the ISBN hyphenation rules. I tried adding `isbn2` (currently at v0.4.0) and `isbnid` (currently at v0.1.3) to `Cargo.toml`, however, both caused compile errors in existing code due to a change in the `uuid` version, e.g.:
> 
> ```
> thoth-export-server/src/specification/handler.rs:35
> no function or associated item named `update_parameter` found for struct `actix_web::web::Path<(std::string::String, uuid::Uuid)>` in the current scope
> function or associated item not found in `actix_web::web::Path<(std::string::String, uuid::Uuid)>`
> ```
> 
> We should discuss whether this can be resolved and therefore whether either of the crates can be used.

This turned out to be a known issue caused by `paperclip` having an improperly-configured dependency on `uuid`. Adding the new crates to `Cargo.toml` changed the `paperclip-core` dependency on `uuid` in `Cargo.lock`, upgrading it from 0.7.4 to 0.8.2, which caused the above compile errors. Manually reverting the `uuid` version in `Cargo.lock` resolved the error and allowed the crates to be used without problems.
