### ISSUE TITLE
Problem with creating new work

### ISSUE THREAD

**Issue by ARKKirchner** [thoth-pub/thoth#252]
Hi, I just tried to create a new work (our new book "Touchscreen Archaeology", https://meson.press/books/touchscreen-archaeology/). I don't know what I did wrong, but I always get an error message (see screenshot attached) and I can't save the work.
![Bildschirmfoto 2021-06-08 um 18 26 16](https://user-images.githubusercontent.com/6224369/121224344-bf912500-c888-11eb-9e79-0a4ce60b13b6.png)

**Comment by ja573** [comment]
@ARKKirchner according to the logs it looks like the database is not happy with the DOI: it expects it in the form of https://doi.org/{PREFIX}/{SUFFIX} (with no "www"). Inputting the DOI like https://doi.org/10.14619/1860 should do the trick

Ross has been working on automatically validating and parsing the DOI on the interface as part of #249 , so these type of input problems should be fixed in the next release

**Comment by ARKKirchner** [comment]
Yes, that's it! Works without the www. Thanks!
