### ISSUE TITLE
Make Location editable

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#324]
**Describe the bug**
You cannot delete/edit a Canonical Location unless you also delete all other Non-Canonical Locations

**To Reproduce**
1. Go to a specific Work, select a specific Publication with more than one Location,
2. Try to delete the Canonical Location or to change its landing page or its Full Text URL

**Expected behavior**
You should be able to delete/edit any of the locations with having to delete all others.

**Comment by rhigman** [comment]
This will have to wait until we implement updating (rather than just deleting and re-adding) objects such as locations. A publication cannot be left without a canonical location, so this behaviour is intentional to prevent this from occurring.

**Comment by vincentwj** [comment]
Understood!

**Comment by rhigman** [comment]
This is becoming more pertinent as Thoth Plus ramps up. Example:

- Publisher enters canonical location with Full Text URL that points to an HTML page, not a PDF (https://github.com/thoth-pub/thoth/issues/439)
- Thoth Plus then disseminates to some additional platforms on publisher's behalf and adds them as non-canonical locations
- Thoth Dissemination Service attempts to disseminate to Internet Archive (currently still only monthly) and fails due to the Full Text URL issue
- Publisher's responsibility to correct canonical location to allow IA resubmission, but this now entails correctly deleting and re-creating additional non-canonical locations not added by them
