### ISSUE TITLE
Limit to 6 the number of ISBNs offered in CrossRef metadata export

### ISSUE THREAD

**Issue by lb803** [thoth-pub/thoth#379]
**Describe the bug**
The [Crossref Metadata Input Schema v. 5.3.1](https://www.crossref.org/schemas/crossref5.3.1.xsd) accepts max 6 ISBNs in a single book DOI deposit. At present, Thoth doesn't seem to limit the number of ISBNs in the CrossRef metadata output.

**To Reproduce**
1. $`curl -X GET "https://export.thoth.pub/specifications/doideposit%3A%3Acrossref/work/2566ed3d-3df1-4e56-a7dc-455ecf7d3a4b"`
2. The output reports 7 ISBNs associated to the work.

**Expected behavior**
Limit the number of ISBNs to 6 in output.

**Desktop (please complete the following information):**
 - OS: Linux
 - Curl
 - Version 7.68.0

**Additional context**
Thank you!

**Comment by rhigman** [comment]
Thanks for raising this - I had thought I'd tested this restriction via [CrossRef's verification tool](https://apps.crossref.org/XSDParse/) and it was fine, but on checking the example you gave, it does produce an error. @rupertgatti's suggestion is to leave out the HTML ISBN in such situations, so I'll try to implement that. He's also planning to raise it with the CrossRef books Working Group as it's obviously a restriction which is unhelpful to some publishers (e.g. us!).

**Comment by rhigman** [comment]
@eshellman Each of OBP's books currently have 7 editions each with separate ISBNs: Paperback, Hardback, PDF, EPUB, HTML, XML, and AZW3. This is the product page for the example in the original bug report: https://www.openbookpublishers.com/product/743.

**Comment by ja573** [comment]
> I'm curious about the book with more than 6 ISBNs. In my experience this happens when a publisher is cheating on edition separation. There are many many books with thousands of editions. I remember when Bowker put out a white paper directing that every digital format should require a separate ISBN, with a list of about 20 digital formats. The book industry for the most part said "Why bless your heart!" and completely ignored that directive, resulting in a royal mess of implementation.

What's your view on this? BISG does recommend assigning a different ISBN to each digital edition. The alternative is what some people call an eISBN, which is quite useless when it comes to distributing the book

**Comment by eshellman** [comment]
Looks like you've done it more or less correctly, in that each ISBN should correspond to a "product". If the website differentiates, then that's what matters.

My view is that you should not assign new ISBNs for derived files unless the derived files are "sold" separately.

Separate ISBNs for TEI and HTML can be superfluous, especially if you derive HTML from the TEI, because you're not going to want a new ISBN when you update your conversion. And you don't want to be inserting ISBNs into derived files; it helps no one to list 7 ISBNs in a source file that get included in 7 different products.

If I take your TEI file and run it through my TEI->* converter, the ISBN should remain the one assigned to the source version - just because I make it into EPUB or PDF or superVHS doesn't make it a new "product".

BISG serves commercial supply chains and is indifferent to non-commercial supply chains, though they mean well.

**Comment by rhigman** [comment]
Output format has now been changed to only include a maximum of 6 ISBNs. If/when CrossRef change this requirement at their end, we should review and amend/revert this.
